"""Regenerate checked-in conversion SPIR-V headers with Vulkan SDK glslc."""
import argparse
import hashlib
import json
from pathlib import Path
import struct
import subprocess
import tempfile

SHADERS = [('convert.vert', 'convert_vert_spv.h', 'CONVERT_VERT_SPV'),
           ('convert.frag', 'convert_frag_spv.h', 'CONVERT_FRAG_SPV'),
           ('ycbcr_to_rgba.comp', 'ycbcr_to_rgba_spv.h', 'YCBCR_TO_RGBA_SPV')]


def manifest(source_dir, output_dir):
    # Git checks these text files out as CRLF on Windows and LF in CI.
    return {name: hashlib.sha256((directory / name).read_bytes().replace(b'\r\n', b'\n')).hexdigest()
            for source, header, _ in SHADERS
            for directory, name in ((source_dir, source), (output_dir, header))}


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--glslc', default='glslc')
    parser.add_argument('--output-dir', type=Path)
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    root = Path(__file__).resolve().parent
    output = args.output_dir or root
    if args.check:
        if json.loads((output / 'shader-manifest.json').read_text()) != manifest(root, output):
            raise SystemExit('Stale pyroclient shaders: regenerate/fold shaders.yml artifacts before building')
        return
    output.mkdir(parents=True, exist_ok=True)
    for source, header, symbol in SHADERS:
        with tempfile.TemporaryDirectory() as tmp:
            out = Path(tmp) / 'shader.spv'
            subprocess.run([args.glslc, '-O', '--target-env=vulkan1.1', str(root/source), '-o', str(out)], check=True)
            data = out.read_bytes(); words = struct.unpack(f'<{len(data)//4}I', data)
        lines = [', '.join(f'0x{w:08x}u' for w in words[i:i+8]) for i in range(0, len(words), 8)]
        (output/header).write_text('// Generated by compile_shaders.py; edit the GLSL source.\n#pragma once\n#include <cstdint>\n'
            f'static const uint32_t {symbol}[] = {{\n    ' + ',\n    '.join(lines) + '\n};\n', newline='\n')

    (output / 'shader-manifest.json').write_text(json.dumps(manifest(root, output), indent=2) + '\n',
                                               encoding='utf-8', newline='\n')


if __name__ == '__main__':
    main()
